jobs:
  setup:
    docker:
      - image: cimg/python:3.13
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            ARBOR_PATH=$(pwd)/src/bin
            echo "Adding \"$ARBOR_PATH\" to \$PATH..."
            echo 'export PATH='"$ARBOR_PATH"':"$PATH"' >> "$BASH_ENV"
            source "$BASH_ENV"
            arbor --help

workflows:
  version: 2
  setup_ci:
    jobs:
      - setup
