[project]
name = "arbor"
version = "1.0.0"
description = ""
authors = [{name = "Platform", email = "platform@ecosia.org"}]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "typer>=0.21.1",
    "click",
]

[tool.uv]
exclude-newer = "3 days"

[project.scripts]
arbo = "arbor.__main__.cli"
